useDotenv: true
configValidationMode: error
unresolvedVariablesNotificationMode: error
variablesResolutionMode: 20210326

service: monada-analytics
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  defaultLambdaCors:
    origin: '*'
    headers:
      - '*'
  dotenvVars: ${file(configs.js)}
  tables:
    submissionsTable: ${self:service}-submissions-${sls:stage}
    usersTable: ${self:service}-users-${sls:stage}
    ratingsTable: ${self:service}-ratings-${sls:stage}
    tosRefusalMessageTable: ${self:service}-tos-refusal-message-${sls:stage}
    accessKey: ${self:service}-access-key-${sls:stage}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: ${self:service}-root-${sls:stage}
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - lambda:*
          Resource: '*'

functions:
  # User Functions
  userCreate:
    handler: src/handlers/users/create.create
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /users/create
          method: POST
    environment:
      SIGNUP_SECRET: ${self:custom.dotenvVars.SIGNUP_SECRET}
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}
      DYNAMODB_ACCESS_KEY_TABLE: ${self:custom.tables.accessKey}

  userInitialize:
    handler: src/handlers/users/initialize.initialize
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /users/initialize
          method: POST
    environment:
      JWT_SECRET: ${self:custom.dotenvVars.JWT_SECRET}
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}

  validateAccessKey:
    handler: src/handlers/users/validate-access-key.validateAccessKey
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /users/status
          method: POST
    environment:
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}
      DYNAMODB_ACCESS_KEY_TABLE: ${self:custom.tables.accessKey}

  # Submissions Functions
  submissionsAddCategory:
    handler: src/handlers/submissions/add-category.addCategory
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /submissions/add-category
          method: POST
    environment:
      DYNAMODB_SUBMISSIONS_TABLE: ${self:custom.tables.submissionsTable}
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}
      JWT_SECRET: ${self:custom.dotenvVars.JWT_SECRET}

  submissionsGet:
    handler: src/handlers/submissions/get.get
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /submissions
          method: GET
    environment:
      DYNAMODB_SUBMISSIONS_TABLE: ${self:custom.tables.submissionsTable}
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}
      JWT_SECRET: ${self:custom.dotenvVars.JWT_SECRET}

  # Ratings functions
  createRating:
    handler: src/handlers/ratings.create
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /ratings
          method: POST
    environment:
      DYNAMODB_RATINGS_TABLE: ${self:custom.tables.ratingsTable}
      DYNAMODB_USERS_TABLE: ${self:custom.tables.usersTable}
      JWT_SECRET: ${self:custom.dotenvVars.JWT_SECRET}

  # TOS Refusal functions
  TOSRefusalMessageCreate:
    handler: src/handlers/tos-refusal/create.create
    events:
      - http:
          cors: ${self:custom.defaultLambdaCors}
          path: /tos-refusal
          method: POST
    environment:
      DYNAMODB_TOS_REFUSAL_MESSAGE_TABLE: ${self:custom.tables.tosRefusalMessageTable}

resources:
  Resources:
    submissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.submissionsTable}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: userCpf
            AttributeType: S
        KeySchema:
          - AttributeName: userCpf
            KeyType: HASH
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.usersTable}
        AttributeDefinitions:
          - AttributeName: cpf
            AttributeType: S
        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
    accessKeys:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.accessKey}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
    ratingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.ratingsTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    tosRefusalMessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.tosRefusalMessageTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
