POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
	"email": "contato@monada.tech",
	"password": "teste123",
	"secret": "super-secret-signup-key-just-for-me"
}

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
	"email": "monada.tech@gmail.com",
	"password": "teste123"
}

###
PATCH http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vbmFkYS50ZWNoQGdtYWlsLmNvbSIsImlhdCI6MTYyMTQ5MzEwNiwiZXhwIjoxNjIyMDk3OTA2fQ.F66vka4szbWzV0yKcz5OtxCwhkLNXxuZGNdncLbBCsQ

{
	"about": {
		"one": 10,
		"two": "20"
	}
}

###

POST http://localhost:3000/submissions HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vbmFkYS50ZWNoQGdtYWlsLmNvbSIsImlhdCI6MTYyMTQ5MzEwNiwiZXhwIjoxNjIyMDk3OTA2fQ.F66vka4szbWzV0yKcz5OtxCwhkLNXxuZGNdncLbBCsQ

{
	"Teste": 120,
	"Teste2": "120"
}