export const sheetsColumnsName = [
	'id',
	'creationDate',
	'userEmail',
	{
		keyName: 'data',
		columns: [
			'message',
			{
				keyName: 'about',
				columns: [
					'wantToKeepHomeOffice',
					'willHomeOfficeWork',
					'race',
					'sexuality',
					'gender',
					'transgender',
					'ageGroup',
					'deficiency',
					'originCountry',
					'originState',
					'civilState',
					'workingState',
					'numberOfPeople',
					'numberOfFinancialDependents',
					'familyIncome',
					'incomePercentage',
					'initialHierarchy',
					'currentHierarchy',
					'workYears',
					'transportMethod',
					'transportTimeLength',
					'adaptationEfficiency',
					'workSatisfaction',
				],
			},
			{
				keyName: 'exclusionCategories',
				columns: [
					'Acesso e participação',
					'Aprendizado e crescimento',
					'Elogio',
					'Equilíbrio entre vida pessoal e profissional',
					'Interações no trabalho',
					'Oportunidades de carreira',
					'Reconhecimento',
					'Respeito',
					'Uso de habilidades e tarefas',
					'Outro',
				],
			},
			{
				keyName: 'exclusionSources',
				columns: [
					'Clientes / Parceiros',
					'Colaboradores',
					'Lideranças',
					'Outro',
					'Políticas da Empresa',
					'Recursos Humanos',
				],
			},
		],
	},
];
